// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.250303.1

#pragma once
#ifndef WINRT_Hot3dxBlankApp2_0_H
#define WINRT_Hot3dxBlankApp2_0_H
WINRT_EXPORT namespace winrt::Windows::UI::Xaml::Markup
{
    struct IXamlMetadataProvider;
}
WINRT_EXPORT namespace winrt::Hot3dxBlankApp2
{
    struct IMainPage;
    struct MainPage;
    struct XamlMetaDataProvider;
}
namespace winrt::impl
{
    template <> struct category<winrt::Hot3dxBlankApp2::IMainPage>{ using type = interface_category; };
    template <> struct category<winrt::Hot3dxBlankApp2::MainPage>{ using type = class_category; };
    template <> struct category<winrt::Hot3dxBlankApp2::XamlMetaDataProvider>{ using type = class_category; };
    template <> inline constexpr auto& name_v<winrt::Hot3dxBlankApp2::MainPage> = L"Hot3dxBlankApp2.MainPage";
    template <> inline constexpr auto& name_v<winrt::Hot3dxBlankApp2::XamlMetaDataProvider> = L"Hot3dxBlankApp2.XamlMetaDataProvider";
    template <> inline constexpr auto& name_v<winrt::Hot3dxBlankApp2::IMainPage> = L"Hot3dxBlankApp2.IMainPage";
    template <> inline constexpr guid guid_v<winrt::Hot3dxBlankApp2::IMainPage>{ 0x80CB814C,0xAD63,0x5723,{ 0xBB,0xE2,0xBA,0xB3,0xA1,0xCF,0x33,0xBD } }; // 80CB814C-AD63-5723-BBE2-BAB3A1CF33BD
    template <> struct default_interface<winrt::Hot3dxBlankApp2::MainPage>{ using type = winrt::Hot3dxBlankApp2::IMainPage; };
    template <> struct default_interface<winrt::Hot3dxBlankApp2::XamlMetaDataProvider>{ using type = winrt::Windows::UI::Xaml::Markup::IXamlMetadataProvider; };
    template <> struct abi<winrt::Hot3dxBlankApp2::IMainPage>
    {
        struct WINRT_IMPL_NOVTABLE type : inspectable_abi
        {
            virtual int32_t __stdcall get_MyProperty(int32_t*) noexcept = 0;
            virtual int32_t __stdcall put_MyProperty(int32_t) noexcept = 0;
        };
    };
    template <typename D>
    struct consume_Hot3dxBlankApp2_IMainPage
    {
        [[nodiscard]] auto MyProperty() const;
        auto MyProperty(int32_t value) const;
    };
    template <> struct consume<winrt::Hot3dxBlankApp2::IMainPage>
    {
        template <typename D> using type = consume_Hot3dxBlankApp2_IMainPage<D>;
    };
}
#endif
